# tmux config file

# general
set -g prefix C-a
set -g prefix2 C-b
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 10000
set -g display-time 1000
set -g status-interval 5
set -g focus-events on
set -g escape-time 10
set -g set-clipboard on

# mouse
set -g mouse on

# key bindings
bind r source-file $HOME/.config/tmux/tmux.conf \;\
  display-message "󰑐 config reloaded"
bind c new-window -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind Tab last-window

# kill binds
bind x confirm-before -p "Kill pane? (y/n)" kill-pane
bind q confirm-before -p "Kill window? (y/n)" kill-window

# vi behavior
# vi copy/paste:
#   - start mode.....: v
#   - move cursor....: hjkl
#   - copy selection.: y
#   - exit mode......: q or esc
#   - paste clipboard: prefix + ]
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# copy-mode-vi enhancements
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# github dark dimmed colorscheme
set -g @gh_red       "#f47067"
set -g @gh_orange    "#daaa3f"
set -g @gh_yellow    "#c69026"
set -g @gh_green     "#57ab5a"
set -g @gh_cyan      "#39c5cf"
set -g @gh_blue      "#539bf5"
set -g @gh_purple    "#b083f0"
set -g @gh_pink      "#ff938a"
set -g @gh_text      "#adbac7"
set -g @gh_subtext1  "#909dab"
set -g @gh_subtext0  "#768390"
set -g @gh_overlay2  "#636e7b"
set -g @gh_overlay1  "#545d68"
set -g @gh_overlay0  "#444c56"
set -g @gh_surface2  "#373e47"
set -g @gh_surface1  "#2d333b"
set -g @gh_surface0  "#272e35"
set -g @gh_base      "#22272e"
set -g @gh_mantle    "#1c2128"
set -g @gh_crust     "#181d23"

# status bar
set -g status-position top
set -g status-style "fg=#{@gh_text},bg=#{@gh_mantle}"

set -g window-status-current-format \
  "#[fg=#{@gh_blue}] #I·#W#[default]"
set -g window-status-format \
  "#[fg=#{@gh_overlay1}] #I·#W#[default]"
set -g window-status-current-style "fg=#{@gh_blue},bg=#{@gh_mantle}"
set -g window-status-style "fg=default,bg=#{@gh_mantle}"

set -g pane-border-style "fg=#{@gh_overlay0}"
set -g pane-active-border-style "fg=#{@gh_cyan}"

set -g message-style "fg=#{@gh_orange},bg=#{@gh_base}"

set -g status-left \
  "#{?client_prefix,#[fg=#{@gh_red}]❯ #{session_name},#[fg=#{@gh_green}]❯ #{session_name}}#[default] "

set -g status-right ""
