test -z "$PS1" && return

test -f /etc/bashrc && . "$_"
test -d $HOME/.local/bin && PATH="$_:$PATH"

stty -ixon
shopt -s checkwinsize
umask 027

export HISTSIZE=1000
export HISTFILESIZE=2000
export HISTCONTROL=ignoreboth
export HISTTIMEFORMAT="%F %T "
export HISTIGNORE="&:[]*:exit:ls:bg:fg:history:clear:pwd"
shopt -s histappend

export PS1="\u@\h:\$?:\W\\$ "
export EDITOR="vim"
export VISUAL="vim"

TMOUT=600
readonly TMOUT
export TMOUT

case "$OSTYPE" in
    linux*)          source "$HOME/.config/aliases.linux.sh"   ;;
    *bsd* | darwin*) source "$HOME/.config/aliases.bsd.sh"     ;;
    msys  | cygwin)  source "$HOME/.config/aliases.windows.sh" ;;
esac
