live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
opacity = 0.75
blur = true
option_as_alt = "both"

[font]
size = 16

[keyboard]
bindings = [
  { key = "PageUp",  action = "ScrollPageUp" },
  { key = "PageDown", action = "ScrollPageDown" }
]
