# alacrity configuration
# https://alacritty.org/config-alacritty.html

[general]
live_config_reload = true

[terminal]
shell = { program = "zsh", args = [] }

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "none"
opacity = 0.75
blur = true
option_as_alt = "both"

[scrolling]
history = 50000

[font]
size = 16
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

[cursor]
style = { shape="underline", blinking="always" }
thickness = 0.3

[mouse]
hide_when_typing = false

[keyboard]
bindings = [
  { key="PageUp",   action="ScrollPageUp" },
  { key="PageDown", action="ScrollPageDown" },
  { key="Up",   mods="Command", action="ScrollPageUp" },
  { key="Down", mods="Command", action="ScrollPageDown" },
]
