# oh-my-posh configuration file - runes
# a simple yet descriptive prompt theme with runes assigned to shells.
# export in json: oh-my-posh config export --output ~/Downloads/runes.json

console_title_template = '{{ .Folder }}'
version = 3
final_space = true

[palette]
# color palette: https://catppuccin.com/palette/
cp_mocha_rosewater = '#f5e0dc'
cp_mocha_flamingo  = '#f2cdcd'
cp_mocha_pink      = '#f5c2e7'
cp_mocha_mauve     = '#cba6f7'
cp_mocha_red       = '#f38ba8'
cp_mocha_maroon    = '#eba0ac'
cp_mocha_peach     = '#fab387'
cp_mocha_yellow    = '#f9e2af'
cp_mocha_green     = '#a6e3a1'
cp_mocha_teal      = '#94e2d5'
cp_mocha_sky       = '#89dceb'
cp_mocha_sapphire  = '#74c7ec'
cp_mocha_blue      = '#89b4fa'
cp_mocha_lavender  = '#b4befe'
cp_mocha_text      = '#cdd6f4'
cp_mocha_subtext1  = '#bac2de'
cp_mocha_subtext0  = '#a6adc8'
cp_mocha_overlay2  = '#9399b2'
cp_mocha_overlay1  = '#7f849c'
cp_mocha_overlay0  = '#6c7086'
cp_mocha_surface2  = '#585b70'
cp_mocha_surface1  = '#45475a'
cp_mocha_surface0  = '#313244'
cp_mocha_base      = '#1e1e2e'
cp_mocha_mantle    = '#181825'
cp_mocha_crust     = '#11111b'

[transient_prompt]
template = '❯ '
foreground = 'p:cp_mocha_text'
background = 'transparent'
foreground_templates = ['{{ if gt .Code 0 }}p:cp_mocha_red{{ end }}']

[secondary_prompt]
template = '❯❯ '
foreground = 'p:cp_mocha_text'
background = 'transparent'

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'session'
style = 'diamond'
leading_diamond = ''
trailing_diamond = ''
template = '{{ if .SSHSession }}󰒍{{ else }}󰟀{{ end }}'
foreground = 'p:cp_mocha_text'
background = 'p:cp_mocha_surface0'

[[blocks.segments]]
type = 'aws'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:cp_mocha_base'
background = 'p:cp_mocha_sky'
template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}'

[[blocks.segments]]
type = 'gcp'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:cp_mocha_base'
background = 'p:cp_mocha_sky'
template = ' {{ .Project }}::{{ .Account }}'

[[blocks.segments]]
type = 'path'
style = 'diamond'
template = '{{ .Path }}'
foreground = 'p:cp_mocha_base'
background = 'p:cp_mocha_teal'

[blocks.segments.properties]
style = 'agnoster_short'
max_depth = 2.0
display_root = true
home_icon = ''
folder_icon = ''
folder_separator_icon = '󰿟'

[[blocks.segments]]
type = 'git'
style = 'accordion'
powerline_symbol = ''
template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} {{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'
foreground = 'p:cp_mocha_base'
background = 'p:cp_mocha_green'
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:cp_mocha_yellow{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:cp_mocha_peach{{ end }}',
  '{{ if gt .Ahead 0 }}p:cp_mocha_red{{ end }}',
  '{{ if gt .Behind 0 }}p:cp_mocha_red{{ end }}',
]

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'
fetch_stash_count = true
branch_template = '{{ trunc 25 .Branch }}'
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
type = 'python'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:cp_mocha_base'
background = 'p:cp_mocha_mauve'
template = '{{ .Major }}.{{ .Minor}}'

[[blocks.segments]]
type = 'go'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:cp_mocha_base'
background = 'p:cp_mocha_flamingo'
template = '{{ .Major }}.{{ .Minor}}'

[[blocks.segments]]
type = 'executiontime'
style = 'accordion'
powerline_symbol = ''
foreground = 'p:cp_mocha_text'
background = 'p:cp_mocha_surface1'
template = '{{ div .Ms 1000 }}s'
always_enabled = true

[blocks.segments.properties]
threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯'
foreground = 'p:cp_mocha_text'
type = 'status'
style = 'diamond'
foreground_templates = ['{{ if gt .Code 0 }}p:cp_mocha_red{{ end }}']

[blocks.segments.properties]
always_enabled = true
