# oh-my-posh configuration file - laguz
# export in json: oh-my-posh config export --output laguz.json

console_title_template = '{{ .Folder }}'
version = 3
final_space = true

[palette]
  fg1 = '#EFDCF9'
  fg2 = '#ae1800'
  bg1 = '#333238'
  bg2 = '#434248'
  bg3 = '#535158'
  bg4 = '#1068bf'
  bg5 = '#108548'
  bg6 = '#ab6100'
  bg7 = '#dd2b0e'

[transient_prompt]
  template = '❯ '
  foreground = 'p:fg1'
  background = 'transparent'
  foreground_templates = ['{{ if gt .Code 0 }}p:fg2{{ end }}']

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:fg1'
  background = 'transparent'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = "{{ .Icon }} "
    foreground = 'p:fg1'
    background = 'p:bg1'
    type = 'os'
    style = 'powerline'

  [[blocks.segments]]
    template = '{{ .Name }} '
    foreground = 'p:fg1'
    powerline_symbol = ''
    background = 'p:bg2'
    type = 'shell'
    style = 'powerline'

    [blocks.segments.properties]
      [blocks.segments.properties.mapped_shell_names]
        bash = 'β'
        cmd = 'C'
        fish = 'ƒ'
        pwsh = 'ψ'
        wsl = 'ψ'
        zsh = 'ζ'

  [[blocks.segments]]
    template = '{{ if .SSHSession }}{{ end }} {{ .UserName }} '
    foreground = 'p:fg1'
    powerline_symbol = ''
    background = 'p:bg3'
    type = 'session'
    style = 'powerline'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:fg1'
    powerline_symbol = ''
    background = 'p:bg4'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = ' ❱ '
      home_icon = '~'
      max_depth = 2.0
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}  {{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }} '
    foreground = 'p:fg1'
    powerline_symbol = ''
    background = 'p:bg5'
    type = 'git'
    style = 'accordion'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:bg6{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:bg6{{ end }}', '{{ if gt .Ahead 0 }}p:bg7{{ end }}', '{{ if gt .Behind 0 }}p:bg7{{ end }}']

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_stash_count = true

      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'accordion'
    powerline_symbol = ''
    foreground = 'p:fg1'
    background = 'p:bg7'
    template = '{{ div .Ms 1000 }}s '

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    foreground = 'p:fg1'
    type = 'status'
    style = 'diamond'
    foreground_templates = ['{{ if gt .Code 0 }}p:fg2{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
