# oh-my-posh configuration file - runes
# a simple yet descriptive prompt theme with runes assigned to shells.
# export in json: oh-my-posh config export --output ~/Downloads/runes.json

console_title_template = '{{ .Folder }}'
version = 3
final_space = true

[palette]
# color palette: https://catppuccin.com/palette/
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'


[transient_prompt]
template = '❯ '
foreground = 'p:text'
background = 'transparent'
foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

[secondary_prompt]
template = '❯❯ '
foreground = 'p:text'
background = 'transparent'

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'os'
style = 'diamond'
leading_diamond = ''
template = '{{ .Icon }} '
foreground = 'p:text'
background = 'p:surface0'

[[blocks.segments]]
type = 'shell'
style = 'diamond'
template = '{{ .Name }} '
foreground = 'p:text'
background = 'p:surface0'

[blocks.segments.properties]
[blocks.segments.properties.mapped_shell_names]
cmd = 'ᛗ'    # Mannaz: humanity, individualism
zsh = 'ᛉ'    # Algiz: protection, defense
elvish = 'ᛇ' # Eiwaz: transformation, resilience
fish = 'ᚠ'   # Fehu: wealth, prosperity
pwsh = 'ᛈ'   # Perthro: mystery, fate
bash = 'ᛒ'   # Berkano: growth, renewal
tcsh = 'ᛏ'   # Tiwaz: justice, leadership
xonsh = 'ᛗ'  # Mannaz: humanity, individualism
shell = 'ᛚ'  # Laguz: water, lake


[[blocks.segments]]
type = 'session'
style = 'diamond'
trailing_diamond = ''
template = '{{ if .SSHSession }}{{ else }}{{ end }}{{ .UserName }}'
foreground = 'p:text'
background = 'p:surface0'

[[blocks.segments]]
type = 'aws'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:base'
background = 'p:sapphire'
template = ' {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }}'

[[blocks.segments]]
type = 'gcp'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:base'
background = 'p:sapphire'
template = ' {{ .Project }}::{{ .Account }}'

[[blocks.segments]]
type = 'path'
style = 'diamond'
template = '{{ .Path }}'
foreground = 'p:base'
background = 'p:blue'

[blocks.segments.properties]
style = 'agnoster_short'
max_depth = 2.0
display_root = true
home_icon = ''
folder_icon = ''
folder_separator_icon = '󰿟'

[[blocks.segments]]
type = 'git'
style = 'accordion'
powerline_symbol = ''
template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} {{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'
foreground = 'p:base'
background = 'p:green'
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:peach{{ end }}',
  '{{ if gt .Ahead 0 }}p:red{{ end }}',
  '{{ if gt .Behind 0 }}p:red{{ end }}',
]

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'
fetch_stash_count = true
branch_template = '{{ trunc 25 .Branch }}'
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
type = 'python'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:base'
background = 'p:mauve'
template = '{{ .Major }}.{{ .Minor}} {{ .Venv }}'

[[blocks.segments]]
type = 'go'
style = 'powerline'
powerline_symbol = ''
foreground = 'p:base'
background = 'p:mauve'
template = '{{ .Major }}.{{ .Minor}}'

[[blocks.segments]]
type = 'executiontime'
style = 'accordion'
powerline_symbol = ''
foreground = 'p:text'
background = 'p:surface1'
template = '{{ div .Ms 1000 }}s'
always_enabled = true

[blocks.segments.properties]
threshold = 5000

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯'
foreground = 'p:text'
type = 'status'
style = 'diamond'
foreground_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

[blocks.segments.properties]
always_enabled = true
